# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Floyd-Warshall algorithm for shortest-path distances and total flows
#'
#' @param C numeric matrix of edge costs
#' @return D matrix of shortest-path distances, i.e. sum of costs along minimising paths
#' @return F matrix of total flows, i.e. sum of inverse costs, along shortest-paths
rcpp_floyd_flow <- function(C) {
    .Call('_intsegration_rcpp_floyd_flow', PACKAGE = 'intsegration', C)
}

#' Floyd-Warshall algorithm for shortest-path distances and total flows
#'
#' Additionally, it computes also the Euclidean length of shortest-paths (sum of Euclidean lengths)
#' and the total Euclidean closeness (sum of reciprocals Euclidean lengths) along shortest-paths.
#' @param C numeric matrix of edge costs
#' @param L numeric matrix of edge (Euclidean) lenghts
#' @return D matrix of shortest-path distances, i.e. sum of costs along minimising paths
#' @return F matrix of total flows, i.e. sum of inverse costs, along shortest-paths
#' @return D_eucl matrix of Euclidean distances along shortest-paths (paths minimising sum of costs)
#' @return F_eucl matrix of total Eucl. flows, i.e. sum of inverse lengths, along shortest-paths
rcpp_floyd_flow_length <- function(C, L) {
    .Call('_intsegration_rcpp_floyd_flow_length', PACKAGE = 'intsegration', C, L)
}

